version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
  redis:
    image: redis:latest
    ports:
     - 6379:6379
    volumes:
     - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
